---
- name: Get list of installed plugins
  command: >
    ./bin/logstash-plugin list
    chdir={{ logstash_install_dir }}
  register: logstash_plugins_list
  environment:
    - https_proxy: "{{ logstash_https_proxy }}"
    - http_proxy: "{{ logstash_http_proxy }}"
  changed_when: false
  when: not ansible_check_mode

- name: Install configured plugins (disabling plugins install={{ logstash_disable_install }})
  command: >
    ./bin/logstash-plugin install {{ item }}
    chdir={{ logstash_install_dir }}
  with_items: "{{ logstash_install_plugins }}"
  environment:
    - https_proxy: "{{ logstash_https_proxy }}"
    - http_proxy: "{{ logstash_http_proxy }}"
  when:
    - logstash_plugins_list.stdout is defined
    - item not in logstash_plugins_list.stdout
    - not ansible_check_mode
  notify:
    - restart logstash
    - restart_service logstash
